set nocompatible
" if filetype is not on and then turned off, vim issues a bad exit status,
" which is a problem for git for example
filetype on
" this needs to be done to guarantee proper plugin loading
filetype off
" enable after plugins are loaded
filetype plugin indent on

" general settings
set ruler
set nonumber
set textwidth=78
set copyindent
set shiftwidth=2           " tab indention
set tabstop=2              " how big is ur tab
set expandtab              " tabs are evil if not spaces
set softtabstop=2          " softtabs are 4 spaces wide
set shiftround
set bs=2                   " backspacing over everything
set incsearch
set ignorecase
set encoding=utf-8
set cursorline

" use open buffers
set switchbuf=useopen
" allow buffers to be hidden
set hidden

" command shortcuts
let mapleader=","


" open ctags definition in new tab
"map <C-\> :tab split<CR>:exec("tag \".expand("<cword>"))<CR>
" open ctags definition in horizontal split
map <C-\> :sp <CR>:exec("tag ".expand("<cword>"))<CR>
" open ctags in vertical split
map <leader>] :vsp <CR>:exec("tag ".expand("<cword>"))<CR>

augroup space_cleaning
  autocmd!
  " remove unneeded spaces for a good whitespace carbon footprint
  autocmd BufWritePre * :%s/\s\+$//e
augroup END

""" spell checking settings
" set the spellfile for added words if it exists
if filereadable($HOME."/.config/vim/vim-spell.add")
  set spellfile=$HOME/.config/vim/vim-spell.add
endif

" rust.vim options
let g:rustfmt_autosave = 1

" set snipple dir
let g:SnippleBaseDir = $HOME . "/.config/snipple/snippets"

" source overrides configs
if filereadable($HOME."/.config/dotoverrides/vimrc")
  exec ":source ". $HOME . "/.config/dotoverrides/vimrc"
endif

" if a session file exists and we didn't pass any other arguments, restore the
" session
if argc() == 0 && filereadable("Session.vim")
  exec "silent :source Session.vim"
endif


