# vim: set ft=ruby:
# things I usually use, installed via (home|linux)brew
def macos?
  RUBY_PLATFORM =~ /darwin/
end

def linux?
  RUBY_PLATFORM =~ /linux/
end

brew "git"
brew "ripgrep"
brew "bat"
brew "fzf"
brew "tmux"
brew "ctags"
brew "gotags"
brew "fd"

if macos?
  cask "1password"
  cask "1password-cli"
  cask "alfred"
  cask "iterm2"
  cask "phoenix"
  # vim, go, and gh are already installed on codespaces
  brew "vim"
  brew "go"
  brew "gh"

  brew "mutt"
end
