#!/bin/bash

set -e

echo "Running codespace specific script..."

# default to codespace user
if [ -z "${USER}" ]; do
  USER=codespace
fi

echo "Changing shell to zsh for ${USER}..."
# Always want to use ZSH as my default shell (e.g. for SSH)
if ! grep -q "${USER}.*/bin/zsh" /etc/passwd
then
  sudo chsh -s /bin/zsh ${USER}
fi

echo "Installing codespace related dotoverrides configs..."
# we need to use the gpg wrapper for codespaces
echo -e "[gpg]\n  program = /.codespaces/bin/gh-gpgsign" > dotoverrides/gitconfig

# set up org specific overrides
if [[ "$CODESPACE_NAME" =~ .*"github".* ]]; then
  echo "Installing GitHub codespace related dotoverrides configs..."
  echo -e "[user]\n  email = mrtazz@github.com" >> dotoverrides/gitconfig
fi

# install linuxbrew suggested packages
sudo apt-get install build-essential
