#!/bin/bash

set -e

echo "Running codespace specific script..."

# default to codespace user
if [ -z "${USER}" ]; then
  USER=codespace
fi

USER_HOME=$(getent passwd $USER | cut -d: -f6)

echo "Changing shell to zsh for ${USER}..."
# Always want to use ZSH as my default shell (e.g. for SSH)
if ! grep -q "${USER}.*/bin/zsh" /etc/passwd
then
  sudo chsh -s /bin/zsh ${USER}
fi

echo "Installing codespace related dotoverrides configs..."
# we need to use the gpg wrapper for codespaces
echo -e "[gpg]\n  program = /.codespaces/bin/gh-gpgsign" > config/dotoverrides/gitconfig

# set up org specific overrides
if [[ "$GITHUB_REPOSITORY" =~ .*"github".* ]]; then
  echo "Installing GitHub codespace related dotoverrides configs..."
  echo -e "[user]\n  email = mrtazz@github.com" >> config/dotoverrides/gitconfig

  echo "Installing go proxy auth"
  echo "machine goproxy.githubapp.com login nobody password ${GOPROXY_TOKEN_GITHUB}" > ${USER_HOME}/.netrc
fi

# install linuxbrew suggested and other packages
sudo apt-get update && sudo apt-get install --assume-yes build-essential kitty-terminfo

# make sure ~/.config doesn't exist on codespaces so I can install my own
if [ -d "${USER_HOME}/.config" ]; then
  rm -rf "${USER_HOME}/.config"
fi

