name: CI

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, labeled]


jobs:

  build:
    name: spec
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install depdendencies
      run: |
        make bundle-install

    - name: run spec
      run: |
        make spec
